### ISSUE TITLE
1.2.6 cannot start: extensionless SDK imports raise ERR_MODULE_NOT_FOUND (regression from #248)

### ISSUE THREAD

**Issue by kjf** [heroku/heroku-mcp-server#249]
`@heroku/mcp-server@1.2.6` — currently `latest` — exits immediately on startup with `ERR_MODULE_NOT_FOUND`, so it can never complete an MCP handshake. Clients surface this as a generic transport error (Claude Code reports `Failed to reconnect to heroku: CONNECTION_CLOSED`), which makes it look like an auth or network problem rather than a startup crash.

No credentials are needed to reproduce.

## Reproduction

```console
$ npx -y @heroku/mcp-server@1.2.6 < /dev/null
Fatal error in main(): Cannot find module '.../@modelcontextprotocol/sdk/dist/esm/server/mcp'
imported from '.../@heroku/mcp-server/dist/index.js'
```

`1.2.5` starts normally and answers `initialize`:

```console
$ npx -y @heroku/mcp-server@1.2.5
Heroku MCP Server running on stdio
{"result":{"protocolVersion":"2024-11-05","serverInfo":{"name":"Heroku MCP Server","version":"1.2.5"}},...}
```

Environment: Node v24.8.0, npm 11.6.0, macOS 15 (arm64). Not platform-specific — it is a module resolution failure.

## Cause

`edd13122` ("deps: fixes multiple Dependabot security advisories", #248) stripped the `.js` extensions from the two SDK imports in `src/index.ts`:

```diff
-import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
-import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
+import { McpServer } from '@modelcontextprotocol/sdk/server/mcp';
+import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio';
```

The SDK's wildcard export does not append an extension on the runtime condition:

```jsonc
"./*": {
  "types":   "./dist/esm/*.d.ts",
  "import":  "./dist/esm/*",      // -> ./dist/esm/server/mcp  (no such file)
  "require": "./dist/cjs/*"
}
```

Node performs no extension substitution for package exports, so the specifier resolves to an extensionless path that does not exist and the process dies before `main()` gets anywhere.

These are the only two extensionless SDK specifiers in the published `dist` — every relative import in the package still carries `.js`, which is why the regression is limited to the entrypoint.

## Why CI did not catch it

The `types` condition on that wildcard *does* append an extension, so TypeScript resolves `@modelcontextprotocol/sdk/server/mcp` to `dist/esm/server/mcp.d.ts` and type-checks clean, while Node fails on the same specifier at runtime.

That `types` key was added to the `./*` wildcard in SDK **1.29.0** — 1.26.0 through 1.28.0 do not have it. Under this repo's `tsconfig.json` (`"module": "nodenext"`, `"moduleResolution": "Node16"`):

| SDK resolved | `tsc --noEmit` |
|---|---|
| 1.28.0 | `error TS2307: Cannot find module '@modelcontextprotocol/sdk/server/mcp'` |
| 1.30.0 | passes |

The declared range is `^1.26.0` and was **not** changed by #248, so nothing in the diff signals the shift. The build simply began resolving a newer SDK that stopped rejecting the bad specifier. A typecheck against the range's floor would have failed; against the ceiling it passes and ships broken.

## Suggested fix

Restore the extensions in `src/index.ts`:

```ts
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
```

Worth considering alongside it, since typechecking alone cannot catch this class of bug:

- A smoke test that spawns the built binary and asserts a successful `initialize` response. It would have caught this in under a second.
- ESLint `import/extensions` set to `ignorePackages`, or `"rewriteRelativeImportExtensions"`-style enforcement, to stop extensionless ESM specifiers reaching `dist`.

## Workaround

Pin to the last good release:

```jsonc
{
  "mcpServers": {
    "heroku": {
      "command": "npx",
      "args": ["-y", "@heroku/mcp-server@1.2.5"],
      "env": { "HEROKU_API_KEY": "..." }
    }
  }
}
```

**Comment by athakur3** [comment]
Still present in `1.2.7`, which is the current `latest` (published 2026-09-03), so the regression is shipping to anyone installing today.

Reproduced in a clean container on a different stack from the one in the report above — Node v22.23.2, `linux/amd64`, no credentials, empty npm cache:

```console
$ docker run --rm -i node:22-slim sh -lc 'npx -y @heroku/mcp-server@1.2.7' < /dev/null
Fatal error in main(): Cannot find module '/tmp/.npm/_npx/396e00f48ce6bc2e/node_modules/@modelcontextprotocol/sdk/dist/esm/server/mcp'
imported from /tmp/.npm/_npx/396e00f48ce6bc2e/node_modules/@heroku/mcp-server/dist/index.js
```

That rules out the macOS/Node 24 pairing in the original report as a factor, which I think supports the diagnosis already in the issue rather than adding to it.

One detail that may be useful for the fix: the subpath is not in the SDK's `exports` map at all. On `@modelcontextprotocol/sdk@1.30.0` — what `^1.26.0` resolves to today — the map's top-level keys are `.`, `./client`, `./server`, `./validation`, `./validation/ajv`, `./validation/cfworker`, so re-adding the `.js` extension to a `dist/esm/...` deep path may still not resolve. `@modelcontextprotocol/sdk/server/mcp.js` is the exported spelling.

Found while measuring MCP server context cost across a set of public servers; heroku has been unmeasurable since this landed, which is how it surfaced.
